#!/bin/sh
# Hand-written oracle for the m0-wire-base-dir task. Not generated by the
# model under test. Builds a sanitizer-instrumented cgen linking all four
# tool/ pieces together (and the rest of src/, which main.c now reaches), and checks that --base-dir (explicit and default)
# actually gates on a real cgen_resolve_base_dir call now.
set -u

SRC=tools/cgen/src/tool/main.c
ROOTS=tools/cgen/src/tool/roots.c
MATCH_OPT=tools/cgen/src/tool/match_option.c
BASE_RESOLVE=tools/cgen/src/tool/base_resolve.c
CGEN=$(mktemp)
WORK=$(mktemp -d)
trap 'rm -f "$CGEN"; rm -rf "$WORK"' EXIT

gcc -std=c2x -I tools/cgen/src -I tools/cgen/gen \
    -fsanitize=address,undefined -fno-sanitize-recover=all -g -O0 \
    "$SRC" "$ROOTS" "$MATCH_OPT" "$BASE_RESOLVE" \
    $(find tools/cgen/src -name '*.c' ! -name main.c ! -name roots.c \
          ! -name match_option.c ! -name base_resolve.c) -o "$CGEN"
if [ $? -ne 0 ]; then
    echo "FAIL: sanitizer build failed (see above)"
    exit 1
fi

failures=0
fail() { echo "FAIL: $1"; failures=$((failures + 1)); }

# --- explicit --base-dir, has keel.k: resolution succeeds, falls through ---
mkdir -p "$WORK/good"
: > "$WORK/good/keel.k"
out=$("$CGEN" --base-dir "$WORK/good" hello.k 2>&1)
code=$?
if [ "$code" != 1 ]; then
    fail "explicit valid base-dir: exit code $code, want 1 (falls through to 'not yet implemented')"
elif ! echo "$out" | grep -q "not yet implemented"; then
    fail "explicit valid base-dir: expected 'not yet implemented', got '$out'"
fi

# --- explicit --base-dir, no keel.k: base-not-found ---
mkdir -p "$WORK/bad"
out=$("$CGEN" --base-dir "$WORK/bad" hello.k 2>&1)
code=$?
if [ "$code" != 2 ]; then
    fail "explicit invalid base-dir: exit code $code, want 2"
elif ! echo "$out" | grep -q '\[base-not-found\]'; then
    fail "explicit invalid base-dir: expected '[base-not-found]' in stderr, got '$out'"
fi

# --- default resolution, synthetic install tree WITH keel.k ---
mkdir -p "$WORK/okinstall/bin" "$WORK/okinstall/lib/base"
: > "$WORK/okinstall/lib/base/keel.k"
cp "$CGEN" "$WORK/okinstall/bin/cgen"
out=$("$WORK/okinstall/bin/cgen" hello.k 2>&1)
code=$?
if [ "$code" != 1 ]; then
    fail "default valid base: exit code $code, want 1"
elif ! echo "$out" | grep -q "not yet implemented"; then
    fail "default valid base: expected 'not yet implemented', got '$out'"
fi

# --- default resolution, synthetic install tree WITHOUT keel.k ---
mkdir -p "$WORK/badinstall/bin" "$WORK/badinstall/lib/base"
cp "$CGEN" "$WORK/badinstall/bin/cgen"
out=$("$WORK/badinstall/bin/cgen" hello.k 2>&1)
code=$?
if [ "$code" != 2 ]; then
    fail "default missing base: exit code $code, want 2"
elif ! echo "$out" | grep -q '\[base-not-found\]'; then
    fail "default missing base: expected '[base-not-found]' in stderr, got '$out'"
fi

if [ "$failures" = 0 ]; then
    echo "ok"
    exit 0
fi
echo "$failures failure(s)"
exit 1
