#!/bin/sh
# Hand-written oracle for `cgen --stop-after=lex` (cgen design §5.1). Run from
# the repository root. Not generated by the model under test.
#
#   1. builds cgen as usual (make -C tools/cgen), and a copy with
#      -fsanitize=address,undefined, which is the one exercised below;
#   2. the fixed cases in oracles/lex/cases.txt must match their .tokens
#      byte for byte;
#   3. every .k in golden/cases and base must lex with no diagnostic (exit 0,
#      empty stderr), and match the independent reference
#      (oracles/lex/reference_lexer.py);
#   4. the lexer diagnostics: diag.k gives exactly diag.stderr and exits 1;
#      diag-base.k, a module of the base, may #define KEEL_ names: nothing on
#      stderr, exit 0.
#
# The .tokens and .stderr files are the expectation: they are NOT regenerated
# from cgen. diag.stderr was checked by hand against lexer-design §4, §6, §8.
set -u
D=tools/harness/oracles/lex
BIN=$(mktemp)
trap 'rm -f "$BIN"' EXIT

make -s -C tools/cgen >/dev/null 2>&1 || { echo "FAIL: make -C tools/cgen"; make -s -C tools/cgen 2>&1 | tail -20; exit 1; }
gcc -std=c2x -I tools/cgen/src -I tools/cgen/gen -Wall -Wextra \
    -fsanitize=address,undefined -fno-sanitize-recover=all -g -O0 \
    $(find tools/cgen/src -name '*.c') -o "$BIN" || { echo "FAIL: compile error (sanitized build)"; exit 1; }

bad=0
while read -r f; do
    [ -n "$f" ] || continue
    exp="$D/$(basename "$f" .k).tokens"
    out=$(timeout 10 "$BIN" --stop-after=lex "$f" 2>&1) || { echo "FAIL: $f — cgen exited $?"; echo "$out" | tail -5; bad=1; continue; }
    printf '%s\n' "$out" | diff -u "$exp" - > /tmp/lexdiff.$$ || {
        echo "FAIL: $f differs from $exp (first lines of the diff):"
        head -20 /tmp/lexdiff.$$
        bad=1
    }
done < "$D/cases.txt"
rm -f /tmp/lexdiff.$$

for f in $(find golden/cases base -name '*.k' | sort); do
    out=$(timeout 10 "$BIN" --stop-after=lex "$f" 2>&1) || { echo "FAIL: $f — cgen exited $?"; echo "$out" | tail -5; bad=1; continue; }
    ref=$(python3 "$D/reference_lexer.py" "$f")
    [ "$out" = "$ref" ] || {
        echo "FAIL: $f disagrees with the reference lexer:"
        printf '%s\n' "$ref" > /tmp/lexref.$$
        printf '%s\n' "$out" | diff -u /tmp/lexref.$$ - | head -12
        rm -f /tmp/lexref.$$
        bad=1
    }
done

out=$(timeout 10 "$BIN" --stop-after=lex "$D/diag.k" 2>&1 >/dev/null); rc=$?
[ $rc -eq 1 ] || { echo "FAIL: $D/diag.k exited $rc, want 1"; bad=1; }
printf '%s\n' "$out" | diff -u "$D/diag.stderr" - > /tmp/lexdiag.$$ || {
    echo "FAIL: $D/diag.k diagnostics differ from diag.stderr:"
    head -20 /tmp/lexdiag.$$
    bad=1
}
rm -f /tmp/lexdiag.$$
out=$(timeout 10 "$BIN" --stop-after=lex "$D/diag-base.k" 2>&1 >/dev/null); rc=$?
[ $rc -eq 0 ] && [ -z "$out" ] || { echo "FAIL: $D/diag-base.k exited $rc: $out"; bad=1; }

[ $bad -eq 0 ] && echo "ok     cgen --stop-after=lex        (cgen design §5.1)"
exit $bad
