#!/bin/sh
# Hand-written oracle for the m1-lexer-skip-trivia task. Not generated by
# the model under test. {output} is substituted with the real path to the
# generated C file by loop.py.
set -u

SRC="$1"
PEEK=tools/cgen/src/engine/lexer_peek.c
TESTMAIN=tools/harness/oracles/m1_lexer_skip_trivia_test_main.c
BIN=$(mktemp)
trap 'rm -f "$BIN"' EXIT

bad=$(grep -nE '^[[:space:]]*#[[:space:]]*include[[:space:]]*<(stdio\.h|stdlib\.h|unistd\.h|fcntl\.h|sys/)' "$SRC" 2>/dev/null)
if [ -n "$bad" ]; then
    echo "FAIL: engine/ must not do I/O (desenho do cgen §3.1):"
    echo "$bad"
    exit 1
fi

if [ ! -f "$PEEK" ]; then
    echo "FAIL: $PEEK not found — m1-lexer-peek must land before this task"
    exit 1
fi

gcc -std=c2x -I tools/cgen/gen -Wall -Wextra \
    -fsanitize=address,undefined -fno-sanitize-recover=all -g -O0 \
    "$SRC" "$PEEK" "$TESTMAIN" -o "$BIN" || {
    echo "FAIL: compile error"
    exit 1
}

# a recognizer that never returns is a failure, not a hang
timeout 10 "$BIN"
rc=$?
[ $rc -eq 124 ] && echo "FAIL: timed out (a loop that does not advance?)"
exit $rc
