#!/bin/sh
# Hand-written oracle for the m1-read-source task. Not generated by the
# model under test. {output} is substituted with the real path to the
# generated C file by loop.py.
set -u

SRC="$1"
TESTMAIN=tools/harness/oracles/m1_read_source_test_main.c
BIN=$(mktemp)
trap 'rm -f "$BIN"' EXIT

gcc -std=c2x -I tools/cgen/gen -Wall -Wextra \
    -fsanitize=address,undefined -fno-sanitize-recover=all -g -O0 \
    "$SRC" "$TESTMAIN" -o "$BIN" || {
    echo "FAIL: compile error"
    exit 1
}

out=$("$BIN" 2>&1)
code=$?

if [ "$code" != 0 ]; then
    echo "FAIL: test binary exited $code"
    echo "$out"
    exit 1
fi

echo "$out" | grep -q '\[source-not-found\]' || {
    echo "FAIL: reading a nonexistent path must print a message ending in ' [source-not-found]' to stderr — got:"
    echo "$out"
    exit 1
}

echo "ok"
