#!/bin/sh
# Hand-written oracle for the m1-token-predicates-shape task. Not
# generated by the model under test. {output} is substituted with the
# real path to the generated C file by loop.py. The predicates read the
# logical spelling, so they link with the splice recognizer (lexer_peek.c).
set -u

SRC="$1"
TESTMAIN=tools/harness/oracles/m1_token_predicates_shape_test_main.c
BIN=$(mktemp)
trap 'rm -f "$BIN"' EXIT

bad=$(grep -nE '^[[:space:]]*#[[:space:]]*include[[:space:]]*<(stdio\.h|stdlib\.h|unistd\.h|fcntl\.h|sys/)' "$SRC" 2>/dev/null)
if [ -n "$bad" ]; then
    echo "FAIL: engine/ must not do I/O (desenho do cgen §3.1):"
    echo "$bad"
    exit 1
fi

gcc -std=c2x -I tools/cgen/gen -Wall -Wextra \
    -fsanitize=address,undefined -fno-sanitize-recover=all -g -O0 \
    "$SRC" tools/cgen/src/engine/lexer_peek.c "$TESTMAIN" -o "$BIN" || {
    echo "FAIL: compile error"
    exit 1
}

"$BIN"
