#!/bin/sh
# Hand-written oracle for `cgen --stop-after=parse` (cgen design §5.2). Run
# from the repository root. Not generated by the model under test.
#
#   sh tools/harness/oracles/m2-parse-dump.sh [header|decl|inst|ilha]
#
# The level is cumulative, and says which lines are compared, so the parser
# can be built in stages (cgen design §9, parser design §3):
#
#   header   module, import, import_c              (pass 1)
#   decl     + decl                                (pass 2, M2 acceptance)
#   inst     + inst                                (pass 3: instances)
#   ilha     + ilha — everything                   (pass 3: islands)
#
# For each case in parse/cases.txt, cgen runs from the case directory, with
# the repository's base, and its stdout — only the lines of the kinds of the
# level — must equal parse/<case>.parse filtered the same way, byte for byte.
# stderr must be empty and the exit code 0.
#
# The .parse files are the expectation, written by hand from the .k and the
# expected C of the golden case: they are NOT regenerated from cgen.
set -u
LEVEL=${1:-ilha}
case $LEVEL in
    header) KINDS='module|import|import_c' ;;
    decl)   KINDS='module|import|import_c|decl' ;;
    inst)   KINDS='module|import|import_c|decl|inst' ;;
    ilha)   KINDS='module|import|import_c|decl|inst|ilha' ;;
    *) echo "usage: $0 [header|decl|inst|ilha]"; exit 2 ;;
esac

ROOT=$(pwd)
D=$ROOT/tools/harness/oracles/parse
BIN=$(mktemp)
trap 'rm -f "$BIN" /tmp/parsediff.$$' EXIT

make -s -C tools/cgen >/dev/null 2>&1 || { echo "FAIL: make -C tools/cgen"; make -s -C tools/cgen 2>&1 | tail -20; exit 1; }
gcc -std=c2x -I tools/cgen/src -I tools/cgen/gen -Wall -Wextra \
    -fsanitize=address,undefined -fno-sanitize-recover=all -g -O0 \
    $(find tools/cgen/src -name '*.c') -o "$BIN" 2>/dev/null ||
    { echo "FAIL: compile error (sanitized build)"; exit 1; }

only() { grep -E "^($KINDS)	" || true; }

bad=0
while read -r c src; do
    [ -n "$c" ] || continue
    exp=$(only < "$D/$c.parse")
    out=$(cd "$ROOT/golden/cases/$c" &&
          timeout 20 "$BIN" --base-dir "$ROOT/base" --stop-after=parse "$src" 2>/tmp/parsediff.$$)
    rc=$?
    err=$(cat /tmp/parsediff.$$)
    if [ $rc -ne 0 ] || [ -n "$err" ]; then
        echo "FAIL: $c/$src — cgen exited $rc"
        printf '%s\n' "$err" | head -5
        bad=1
        continue
    fi
    printf '%s\n' "$out" | only > /tmp/parsediff.$$.got
    printf '%s\n' "$exp" | diff -u - /tmp/parsediff.$$.got > /tmp/parsediff.$$ || {
        echo "FAIL: $c/$src differs from parse/$c.parse at level $LEVEL:"
        head -20 /tmp/parsediff.$$
        bad=1
    }
    rm -f /tmp/parsediff.$$.got
done < "$D/cases.txt"

[ $bad -eq 0 ] && echo "ok     cgen --stop-after=parse      (cgen design §5.2, level $LEVEL)"
exit $bad
