/* engine/diag.h — the diagnostics sink (diag-design §2, §3). The engine
 * accumulates; tool/report.c prints. engine/: no I/O, no allocation — the
 * caller gives the storage. */
#ifndef CGEN_ENGINE_DIAG_H
#define CGEN_ENGINE_DIAG_H

#include <stdbool.h>
#include <stddef.h>
#include "keel/keel_slice_char.type.h"

typedef enum { K_INFO, K_WARNING, K_ERROR, K_SEVERITY_COUNT } KSeverity;

/* Identifiers the tool spec (§7) owns, and the implementation's own: they are
   not in the language's catalog. */
#define K_DIAG_TOOL(X) \
    X(MODULE_NOT_FOUND, "module-not-found", K_ERROR) \
    X(PARSE_FAILED, "unexpected-token", K_ERROR) \
    X(LOAD_FAILED, "module-load-failed", K_ERROR) \
    X(CAPACITY, "implementation-limit", K_ERROR)

/* The catalog of keel-spec §6.2, generated by tools/cgen/gen-diags.py [G1]:
   K_DIAG_CATALOG(X) lists every diagnostic the translation can emit. */
#include "engine/diag_catalog.def"

/* Index into k_diags: the tool's identifiers, then the catalog's in the spec's
   order. The name of each is K_DIAG_ and the identifier in capitals. */
typedef enum {
#define K_DIAG_ENUM(NAME, ID, SEV) K_DIAG_##NAME,
    K_DIAG_TOOL(K_DIAG_ENUM)
    K_DIAG_CATALOG(K_DIAG_ENUM)
#undef K_DIAG_ENUM
    K_DIAG_COUNT
} KDiagId;

typedef struct {
    const char *name;       /* kebab-case, the catalog's */
    KSeverity   severity;
} KDiagEntry;

extern const KDiagEntry k_diags[K_DIAG_COUNT];

/* The message, written by hand in diag.c: what was found and, when there is
   one, the correct form [G2]. Each %s takes the next argument. A diagnostic
   whose message is not written yet says so, and names itself. */
const char *k_diag_message(KDiagId id);

#define K_DIAG_MAX_ARGS 3

/* the message's holes, as views: of the source, or of a static string */
typedef struct {
    keel_slice_char s[K_DIAG_MAX_ARGS];
} KDiagArgs;

typedef struct {
    KDiagId         id;
    KSeverity       severity;   /* the table's; -Werror is the tool's [G4] */
    keel_slice_char at;         /* a view of the source: position and extent */
    KDiagArgs       args;
} KDiagnostic;

typedef struct {
    KDiagnostic *items;         /* the caller's storage */
    size_t       cap;
    size_t       len;           /* kept, at most cap */
    size_t       count[K_SEVERITY_COUNT];   /* emitted, kept or not */
} KDiagnosticSink;

void   k_diag_init(KDiagnosticSink *s, KDiagnostic *storage, size_t cap);
void   k_diag_emit(KDiagnosticSink *s, KDiagId id, keel_slice_char at, KDiagArgs args);
size_t k_diag_count(const KDiagnosticSink *s, KSeverity sev);

/* a view of a NUL-terminated static string, for a message argument */
keel_slice_char k_diag_text(const char *s);

#endif /* CGEN_ENGINE_DIAG_H */
