#!/bin/sh
# Hand-written oracle for the m0-base-resolve task. Not generated by the
# model under test. {output} is substituted with the real path to the
# generated C file by loop.py.
set -u

SRC=tools/cgen/src/tool/base_resolve.c

TESTMAIN=tools/cgen/test/unit/base_resolve_main.c
BIN=$(mktemp)
WORK=$(mktemp -d)
trap 'rm -f "$BIN"; rm -rf "$WORK"' EXIT

gcc -std=c11 -Wall -Wextra -O0 -g "$SRC" "$TESTMAIN" -o "$BIN" || {
    echo "FAIL: compile error"
    exit 1
}

failures=0
fail() { echo "FAIL: $1"; failures=$((failures + 1)); }

# --- A: explicit dir, has keel.k ---
mkdir -p "$WORK/a"
: > "$WORK/a/keel.k"
out=$("$BIN" "$WORK/a")
code=$?
[ "$code" = 0 ] || fail "explicit+keel.k: exit code $code"
[ -f "$out/keel.k" ] || fail "explicit+keel.k: resolved path '$out' has no keel.k"

# --- B: explicit dir, no keel.k ---
mkdir -p "$WORK/b"
"$BIN" "$WORK/b" >/dev/null 2>"$WORK/b.err"
code=$?
[ "$code" != 0 ] || fail "explicit without keel.k: expected nonzero exit"
grep -q '\[base-not-found\]' "$WORK/b.err" || fail "explicit without keel.k: missing [base-not-found] in stderr: $(cat "$WORK/b.err")"

# --- C: no explicit dir, synthetic install tree WITH keel.k ---
mkdir -p "$WORK/c/bin" "$WORK/c/lib/base"
: > "$WORK/c/lib/base/keel.k"
cp "$BIN" "$WORK/c/bin/cgen_test"
out=$("$WORK/c/bin/cgen_test")
code=$?
[ "$code" = 0 ] || fail "default resolution: exit code $code"
if [ "$code" = 0 ]; then
    resolved_real=$(realpath "$out" 2>/dev/null || echo "$out")
    want_real=$(realpath "$WORK/c/lib/base")
    [ "$resolved_real" = "$want_real" ] || fail "default resolution: got '$resolved_real', want '$want_real'"
fi

# --- D: no explicit dir, synthetic install tree WITHOUT keel.k ---
mkdir -p "$WORK/d/bin" "$WORK/d/lib/base"
cp "$BIN" "$WORK/d/bin/cgen_test"
"$WORK/d/bin/cgen_test" >/dev/null 2>"$WORK/d.err"
code=$?
[ "$code" != 0 ] || fail "default without keel.k: expected nonzero exit"
grep -q '\[base-not-found\]' "$WORK/d.err" || fail "default without keel.k: missing [base-not-found] in stderr: $(cat "$WORK/d.err")"

if [ "$failures" = 0 ]; then
    echo "ok"
    exit 0
fi
echo "$failures failure(s)"
exit 1
