#!/bin/sh
# Hand-written oracle for the m0-match-long-option task. Not generated by
# the model under test. {output} is substituted with the real path to the
# generated C file by loop.py.
set -u

SRC=tools/cgen/src/tool/match_option.c
TESTMAIN=tools/cgen/test/unit/match_option_main.c
BIN=$(mktemp)
trap 'rm -f "$BIN"' EXIT

gcc -std=c11 -Wall -Wextra -fsanitize=address,undefined -g -O0 \
    "$SRC" "$TESTMAIN" -o "$BIN" || {
    echo "FAIL: compile error"
    exit 1
}

"$BIN"
