/* Unit test of engine/, for k_dump_module — a self-contained synthetic
 * module (no import actually resolved; "wrap" is declared and used in
 * the same file, sidestepping the missing KLoader). Expected output
 * hand-derived from the grammar and cgen-tool.md §5.2's dump format, not
 * generated by running cgen. Not model-generated. */
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "engine/parser.h"

static const char *SRC =
    "module demo.mod;\n"
    "\n"
    "import keel.buffer as buffer types;\n"
    "import_c <stdio.h>;\n"
    "\n"
    "pub modifier wrap { i32 v; }\n"
    "\n"
    "pub tags Color [RED, GREEN, BLUE];\n"
    "\n"
    "pub struct Point { i32 x; i32 y; };\n"
    "\n"
    "pub constexpr size_t MAX = 100;\n"
    "\n"
    "pub wrap counter;\n";

static const char *WANT =
    "module\tdemo.mod\t1:1\n"
    "import\tkeel.buffer as buffer types\t3:1\n"
    "import_c\t<stdio.h>\t4:1\n"
    "decl\tpub modifier\twrap\tdemo_mod_wrap\t6:5\n"
    "decl\tpub tags\tColor\tdemo_mod_Color\t8:5\n"
    "decl\tpub type\tPoint\tdemo_mod_Point\t10:5\n"
    "decl\tpub constexpr\tMAX\tdemo_mod_MAX\t12:5\n"
    "decl\tpub var\tcounter\tdemo_mod_counter\t14:5\n";

int main(void) {
    keel_slice_char source = { strlen(SRC), (char *)SRC };
    KSymbol storage[16];

    size_t needed = k_dump_module(source, storage, 16, (keel_slice_char){0});
    char *buf = malloc(needed + 1);
    if (!buf) { fprintf(stderr, "FAIL: malloc\n"); return 1; }
    size_t written = k_dump_module(source, storage, 16, (keel_slice_char){ needed, buf });

    int failures = 0;
    if (written != needed) {
        fprintf(stderr, "FAIL: sizing pass (%zu) != filling pass (%zu)\n", needed, written);
        failures++;
    }
    size_t want_len = strlen(WANT);
    if (written != want_len || memcmp(buf, WANT, want_len) != 0) {
        fprintf(stderr, "FAIL: dump mismatch.\n--- got (%zu bytes) ---\n%.*s\n--- want (%zu bytes) ---\n%s\n",
                written, (int)written, buf, want_len, WANT);
        failures++;
    }

    free(buf);
    if (failures == 0) { puts("ok"); return 0; }
    fprintf(stderr, "%d failure(s)\n", failures);
    return 1;
}
