/* Unit test of engine/: AST and dump from a self-contained synthetic
 * module (no import actually resolved; "wrap" is declared and used in
 * the same file, sidestepping the missing KLoader). Expected output
 * hand-derived from the grammar and cgen-tool.md §5.2's dump format, not
 * generated by running cgen. Not model-generated. */
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "engine/ast.h"

static const char *SRC =
    "module demo.mod type T;\n"
    "\n"
    "import keel.buffer as buffer types;\n"
    "import_c <stdio.h>;\n"
    "\n"
    "pub modifier wrap { i32 v; }\n"
    "\n"
    "pub tags Color [RED, GREEN, BLUE];\n"
    "\n"
    "pub struct Point { i32 x; i32 y; };\n"
    "\n"
    "pub constexpr size_t MAX = 100;\n"
    "\n"
    "pub wrap counter;\n"
    "pub i32 f(void) { return 1; }\n";

static const char *WANT =
    "module\tdemo.mod\t1:1\n"
    "import\tkeel.buffer as buffer types\t3:1\n"
    "import_c\t<stdio.h>\t4:1\n"
    "decl\tpub modifier\twrap\tdemo_mod_wrap\t6:1\n"
    "decl\tpub tags\tColor\tdemo_mod_Color\t8:1\n"
    "decl\tpub type\tPoint\tdemo_mod_Point\t10:1\n"
    "decl\tpub constexpr\tMAX\tdemo_mod_MAX\t12:1\n"
    "decl\tpub var\tcounter\tdemo_mod_counter\t14:1\n"
    "decl\tpub func\tf\tdemo_mod_f\t15:1\n";

int main(void) {
    keel_slice_char source = { strlen(SRC), (char *)SRC };
    size_t count = k_lexemes(source, NULL, 0, NULL);
    KLexeme *tokens = calloc(count + 1, sizeof *tokens);
    KAstNode *nodes = calloc(count + 1, sizeof *nodes);
    if (!tokens || !nodes) return 1;
    k_lexemes(source, tokens, count, NULL);
    KAst ast = { .source = source, .tokens = keel_buffer_KLexeme_of(tokens,count), .nodes = keel_buffer_KAstNode_from(nodes,count+1) };
    if (!k_parse_ast(&ast)) return 1;
    if (ast.nodes.len != 9 || nodes[0].kind != K_AST_MODULE ||
        nodes[0].type_end != nodes[0].type_first + 1 ||
        !k_token_is_ident_named(keel_buffer_KLexeme_ptr(&ast.tokens, nodes[0].type_first)->token, "T") ||
        nodes[1].kind != K_AST_IMPORT || nodes[5].kind != K_AST_TYPE ||
        nodes[5].body_first == (size_t)-1 ||
        nodes[5].first >= nodes[5].end ||
        nodes[5].end > ast.tokens.len ||
        nodes[8].kind != K_AST_FUNCTION ||
        nodes[8].body_first >= nodes[8].body_end ||
        !k_token_is_c_word_named(keel_buffer_KLexeme_ptr(&ast.tokens, nodes[8].body_first)->token, "return")) {
        fprintf(stderr, "FAIL: AST kinds or token spans\n");
        return 1;
    }
    size_t needed = k_dump_ast(&ast, NULL, (keel_slice_char){0});
    char *buf = malloc(needed + 1);
    if (!buf) { fprintf(stderr, "FAIL: malloc\n"); return 1; }
    size_t written = k_dump_ast(&ast, NULL, (keel_slice_char){ needed, buf });

    int failures = 0;
    if (written != needed) {
        fprintf(stderr, "FAIL: sizing pass (%zu) != filling pass (%zu)\n", needed, written);
        failures++;
    }
    size_t want_len = strlen(WANT);
    if (written != want_len || memcmp(buf, WANT, want_len) != 0) {
        fprintf(stderr, "FAIL: dump mismatch.\n--- got (%zu bytes) ---\n%.*s\n--- want (%zu bytes) ---\n%s\n",
                written, (int)written, buf, want_len, WANT);
        failures++;
    }

    free(buf);
    free(tokens);
    free(nodes);
    if (failures == 0) { puts("ok"); return 0; }
    fprintf(stderr, "%d failure(s)\n", failures);
    return 1;
}
