; keel — highlighting on top of the C grammar (tree-sitter-c).
; GENERATED by editors/generate.py: editors/c-highlights.scm + keel-spec.md §2.2.
; Do not edit by hand.
;
; The parser is C's, so keel constructs land in error nodes or become
; identifiers. The rules below match by SPELLING, which works in both cases —
; the same discipline as §2.2: a word counts by position, and here it is
; highlighted by how it is written.

; C rules for tree-sitter-c v0.24.2, with captures Zed recognizes.
; The generator inserts the spec's vocabulary into the type filter so that a
; generic C rule does not compete with keel's highlighting for the same word.

(comment) @comment
(string_literal) @string
(system_lib_string) @string
(char_literal) @string
(escape_sequence) @string.escape
(number_literal) @number
[(true) (false)] @boolean
(null) @constant.builtin

(primitive_type) @type.builtin
(sized_type_specifier) @type.builtin
((type_identifier) @type
 (#not-match? @type "^(constexpr|ptrdiff_t|uintptr_t|extern_c|import_c|instance|modifier|parallel|foreach|outcome|routine|buffer|import|module|size_t|tagged|apply|arena|array|byref|corot|defer|later|match|range|slice|types|bf16|fail|priv|tags|type|walk|ALL|ANY|dim|f16|f32|f64|i16|i32|i64|now|pub|ref|u16|u32|u64|win|as|i8|u8)$"))
(field_identifier) @property
(statement_identifier) @label

(function_declarator
 declarator: (identifier) @function)
(call_expression
 function: (identifier) @function)
(call_expression
 function: (field_expression field: (field_identifier) @function))

[
 "if" "else" "switch" "case" "default"
 "for" "while" "do" "break" "continue" "goto" "return"
 "struct" "union" "enum" "typedef"
 "const" "volatile" "restrict" "static" "extern" "inline"
 "auto" "register" "sizeof" "_Alignof" "_Alignas" "_Atomic"
 "alignof" "alignas" "_Generic" "_Noreturn" "thread_local" "constexpr"
] @keyword

[
 "#include" "#define" "#if" "#ifdef" "#ifndef"
 "#elif" "#else" "#endif"
] @preproc
(preproc_directive) @preproc

["(" ")" "[" "]" "{" "}"] @punctuation.bracket
[";" "," "." "->" ":"] @punctuation.delimiter
[
 "=" "+" "-" "*" "/" "%" "++" "--"
 "==" "!=" "<" ">" "<=" ">="
 "!" "&&" "||" "&" "|" "^" "~" "<<" ">>"
 "+=" "-=" "*=" "/=" "%=" "&=" "|=" "^=" "<<=" ">>=" "?"
] @operator


; keel vocabulary, added to the C rules.

((identifier) @keyword
 (#match? @keyword "^(constexpr|extern_c|import_c|instance|modifier|parallel|foreach|import|module|apply|array|byref|defer|later|match|types|fail|priv|tags|type|walk|ALL|ANY|dim|now|pub|ref|win|as)$"))

((type_identifier) @keyword
 (#match? @keyword "^(constexpr|extern_c|import_c|instance|modifier|parallel|foreach|import|module|apply|array|byref|defer|later|match|types|fail|priv|tags|type|walk|ALL|ANY|dim|now|pub|ref|win|as)$"))

((identifier) @type.builtin
 (#match? @type.builtin "^(ptrdiff_t|uintptr_t|size_t|bf16|f16|f32|f64|i16|i32|i64|u16|u32|u64|i8|u8)$"))

((type_identifier) @type.builtin
 (#match? @type.builtin "^(ptrdiff_t|uintptr_t|size_t|bf16|f16|f32|f64|i16|i32|i64|u16|u32|u64|i8|u8)$"))

((identifier) @type
 (#match? @type "^(outcome|routine|buffer|tagged|arena|corot|range|slice)$"))

((type_identifier) @type
 (#match? @type "^(outcome|routine|buffer|tagged|arena|corot|range|slice)$"))
