#!/usr/bin/env python3
"""Generates the syntax highlighting from keel-spec.md.

The word list is §2.2's, read from the document — not typed here. If the spec
gains or loses a word, running this again is what keeps the editors current.
Usage:  python3 editors/generate.py
"""
import json, pathlib, re, sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
spec = (ROOT / "keel-spec.md").read_text(encoding="utf-8")

def table(section, end):
    body = spec.split(section, 1)[1].split(end, 1)[0]
    return {g: re.findall(r'`([A-Za-z_][A-Za-z0-9_]*)`', p)
            for g, p in re.findall(r'^\| ([^|]+?) \| (.+?) \|$', body, re.M)}

# the spec's prose is in Portuguese: these are its section and row titles
g = table("#### Vocabulário do núcleo", "#### Palavras C reconhecidas")
WORDS = {
    "unit":        g["Unidade e visibilidade"],
    "type":        g["Tipos, marcadores e genéricos"],
    "flow":        g["Fluxo"],
    "tagged":      g["Valores etiquetados"],
}
# `else` is a C word: the C grammar highlights it, not us.
PRIMITIVES = ["i8","i16","i32","i64","u8","u16","u32","u64",
              "f16","bf16","f32","f64","size_t","ptrdiff_t","uintptr_t"]
# names injected by `import … types`: not words, but they read as types.
# `parallel` is left out: it is a core word, already in the flow group — §2.2
# records it as the one name in both positions.
BASE = ["arena","buffer","slice","range","tagged","outcome","corot","routine"]
# `cursor`, `slot` and `control` are left out: `types` injects them too, but
# they are common words in C, and highlighting by spelling is a heuristic — a
# false positive on a user identifier costs more than the highlight gained.

def alt(xs): return "|".join(sorted(xs, key=lambda w: (-len(w), w)))
every = sum(WORDS.values(), [])

# ---------------------------------------------------------------- VSCode
#
# There are TWO files, and the reason was measured: with one, `"include":
# "source.c"` does not reach inside functions — the C block rule takes over and
# only its patterns apply there. `defer` came out as `meta.block.c` and
# `foreach` as `entity.name.function.c`, which is where nearly every keel word
# lives. The base grammar gives C; the INJECTION puts the words in every nested
# scope.
patterns = [
    {"name": "keyword.control.keel",        "match": r"\b(%s)\b" % alt(WORDS["flow"] + WORDS["tagged"])},
    {"name": "keyword.other.keel",          "match": r"\b(%s)\b" % alt(WORDS["unit"] + WORDS["type"])},
    {"name": "support.type.primitive.keel", "match": r"\b(%s)\b" % alt(PRIMITIVES)},
    {"name": "support.type.base.keel",      "match": r"\b(%s)\b" % alt(BASE)},
    # `0..4`: C's number rule matches from the `0` and would swallow the `..`
    # as a malformed number. Matching the left operand along with it, the
    # injection wins by position — measured; without it the range is not
    # highlighted.
    {"match": r"(?<![\w.])(\d+)(\.\.)",
     "captures": {"1": {"name": "constant.numeric.decimal.c"},
                  "2": {"name": "keyword.operator.range.keel"}}},
    {"name": "keyword.operator.range.keel", "match": r"(?<!\.)\.\.(?!\.)"},
]
SCHEMA = "https://raw.githubusercontent.com/martinring/tmlanguage/master/tmlanguage.json"
base = {"$schema": SCHEMA, "name": "keel", "scopeName": "source.keel",
        "fileTypes": ["k"], "patterns": [{"include": "source.c"}]}
inj  = {"$schema": SCHEMA, "name": "keel (injection)", "scopeName": "keel.injection",
        # L: takes precedence over the C rules already in scope
        # `-comment -string`: without it, `defer` in a comment and `buffer` in
        # a string came out highlighted — measured.
        "injectionSelector": "L:source.keel -comment -string", "patterns": patterns}

vs = ROOT / "editors/vscode"
(vs / "syntaxes").mkdir(parents=True, exist_ok=True)
(vs / "syntaxes/keel.tmLanguage.json").write_text(json.dumps(base, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
(vs / "syntaxes/keel-injection.tmLanguage.json").write_text(json.dumps(inj, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")

# ---------------------------------------------------------------- Zed
zd = ROOT / "editors/zed/languages/keel"
zd.mkdir(parents=True, exist_ok=True)
c_highlights = (ROOT / "editors/c-highlights.scm").read_text(encoding="utf-8")
c_highlights = c_highlights.replace("__KEEL_WORDS__", alt(every + PRIMITIVES + BASE))
(zd / "highlights.scm").write_text(f"""; keel — highlighting on top of the C grammar (tree-sitter-c).
; GENERATED by editors/generate.py: editors/c-highlights.scm + keel-spec.md §2.2.
; Do not edit by hand.
;
; The parser is C's, so keel constructs land in error nodes or become
; identifiers. The rules below match by SPELLING, which works in both cases —
; the same discipline as §2.2: a word counts by position, and here it is
; highlighted by how it is written.

{c_highlights}

; keel vocabulary, added to the C rules.

((identifier) @keyword
 (#match? @keyword "^({alt(every)})$"))

((type_identifier) @keyword
 (#match? @keyword "^({alt(every)})$"))

((identifier) @type.builtin
 (#match? @type.builtin "^({alt(PRIMITIVES)})$"))

((type_identifier) @type.builtin
 (#match? @type.builtin "^({alt(PRIMITIVES)})$"))

((identifier) @type
 (#match? @type "^({alt(BASE)})$"))

((type_identifier) @type
 (#match? @type "^({alt(BASE)})$"))
""", encoding="utf-8")

# ------------------------------------------------------- check
# Every word read from the spec must appear in both artifacts. That is what
# catches a renamed section: the table stops being read and the highlighting
# silently empties.
missing = []
vs_txt = (vs / "syntaxes/keel-injection.tmLanguage.json").read_text(encoding="utf-8")
zd_txt = (zd / "highlights.scm").read_text(encoding="utf-8")
for w in every + PRIMITIVES + BASE:
    if not re.search(r"\b%s\b" % re.escape(w), vs_txt): missing.append(("vscode", w))
    if not re.search(r"\b%s\b" % re.escape(w), zd_txt): missing.append(("zed", w))
if missing:
    for target, w in missing: print("MISSING %-7s %s" % (target, w), file=sys.stderr)
    sys.exit(1)

print("words from §2.2: %d" % len(every))
for k, v in WORDS.items():
    print("  %-12s %s" % (k, " ".join(v)))
print("generated: editors/vscode/syntaxes/keel.tmLanguage.json")
print("generated: editors/zed/languages/keel/highlights.scm")
