#!/bin/sh
# Hand-written oracle for `cgen --stop-after=parse` (cgen design §5.2). Run
# from the repository root. Not generated by the model under test.
#
#   sh tools/cgen/test/parse_dump.sh [header|decl|inst|ilha]
#
# The level is cumulative, and says which lines are compared, so the parser
# can be built in stages (cgen design §9, parser design §3):
#
#   header   module, import, import_c              (pass 1)
#   decl     + decl                                (pass 2, M2 acceptance)
#   inst     + inst                                (pass 3: instances)
#   ilha     + closure, unavailable, ilha — everything (pass 3: the closure
#            of the instances and the islands)
#
# A case may name, as a third field in cases.txt, the last level its .parse
# file covers. Asked for a level beyond it, the case reports `wip` and is
# skipped — the same marker golden/run.sh uses for a case under construction
# (golden/README.md), and for the same reason: a .parse written only up to
# `decl` is an incomplete oracle, not a failing one.
#
# For each case in parse/cases.txt, cgen runs from the case directory, with
# the repository's base, and its stdout — only the lines of the kinds of the
# level — must equal parse/<case>.parse filtered the same way, byte for byte.
# stderr must hold no error (warnings and infos are allowed) and the exit
# code must be 0.
#
# The .parse files are the expectation, written by hand from the .k and the
# expected C of the golden case: they are NOT regenerated from cgen.
set -u
LEVEL=${1:-ilha}
# `ilha:<kind>,<kind>...` compares only those kinds of island — the stages of
# parser design §3.2 (4a..4i), while the .parse files stay whole. Plain `ilha`
# compares every kind.
ISLANDS=
case $LEVEL in
    ilha:*) ISLANDS=$(printf '%s' "${LEVEL#ilha:}" | tr ',' '|'); LEVEL=ilha ;;
esac
rank() {
    case $1 in
        header) echo 1 ;; decl) echo 2 ;; inst) echo 3 ;; ilha) echo 4 ;;
        *) echo 0 ;;
    esac
}
case $LEVEL in
    header) KINDS='module|import|import_c' ;;
    decl)   KINDS='module|import|import_c|decl' ;;
    inst)   KINDS='module|import|import_c|decl|inst' ;;
    ilha)   KINDS='module|import|import_c|decl|inst|closure|unavailable|ilha' ;;
    *) echo "usage: $0 [header|decl|inst|ilha[:<island kinds>]]"; exit 2 ;;
esac
WANT=$(rank "$LEVEL")
[ -n "$ISLANDS" ] && KINDS="module|import|import_c|decl|inst"
[ -n "$ISLANDS" ] && LEVEL="ilha:$ISLANDS"

ROOT=$(pwd)
D=$ROOT/tools/cgen/test/parse
BIN=$(mktemp)
trap 'rm -f "$BIN" /tmp/parsediff.$$' EXIT

make -s -C tools/cgen >/dev/null 2>&1 || { echo "FAIL: make -C tools/cgen"; make -s -C tools/cgen 2>&1 | tail -20; exit 1; }
gcc -std=c2x -I tools/cgen/src -I tools/cgen/gen -Wall -Wextra \
    -fsanitize=address,undefined -fno-sanitize-recover=all -g -O0 \
    $(find tools/cgen/src -name '*.c') -o "$BIN" 2>/dev/null ||
    { echo "FAIL: compile error (sanitized build)"; exit 1; }

if [ -n "$ISLANDS" ]; then
    only() { grep -E "^($KINDS)	|^ilha	($ISLANDS)	" || true; }
else
    only() { grep -E "^($KINDS)	" || true; }
fi

bad=0
wip=0
while read -r c src covers; do
    [ -n "$c" ] || continue
    if [ -n "${covers:-}" ] && [ "$(rank "$covers")" -lt "$WANT" ]; then
        echo "wip    $c — .parse cobre até '$covers', pedido '$LEVEL'"
        wip=$((wip + 1))
        continue
    fi
    exp=$(only < "$D/$c.parse")
    if [ -z "$exp" ]; then
        echo "FAIL: parse/$c.parse has no expected lines at level $LEVEL"
        bad=1
        continue
    fi
    out=$(cd "$ROOT/golden/cases/$c" &&
          timeout 20 "$BIN" --base-dir "$ROOT/base" --stop-after=parse "$src" 2>/tmp/parsediff.$$)
    rc=$?
    # warnings and infos come out on stderr by default (diag-design R1): only an
    # error fails the case
    err=$(grep ': error: ' /tmp/parsediff.$$ || true)
    if [ $rc -ne 0 ] || [ -n "$err" ]; then
        echo "FAIL: $c/$src — cgen exited $rc"
        printf '%s\n' "$err" | head -5
        bad=1
        continue
    fi
    printf '%s\n' "$out" | only > /tmp/parsediff.$$.got
    printf '%s\n' "$exp" | diff -u - /tmp/parsediff.$$.got > /tmp/parsediff.$$ || {
        echo "FAIL: $c/$src differs from parse/$c.parse at level $LEVEL:"
        head -20 /tmp/parsediff.$$
        bad=1
    }
    rm -f /tmp/parsediff.$$.got
done < "$D/cases.txt"

[ $bad -eq 0 ] && echo "ok     cgen --stop-after=parse      (cgen design §5.2, level $LEVEL, $wip wip)"
exit $bad
