#!/usr/bin/env python3
"""Generates src/engine/diag_catalog.def from the catalog of keel-spec.md §6.2
(diag-design [G1]): the catalog and the implementation cannot drift apart
without breaking the build. Only the messages are written by hand, in
src/engine/diag.c.

    python3 tools/cgen/gen-diags.py            # rewrite the file
    python3 tools/cgen/gen-diags.py --check    # fail if it is out of date

The `debug` rows are checks the generated program makes when it runs, not
diagnostics of the translation: the tool never emits them, so they are not
in the table. --list prints every identifier of the catalog with its severity,
for the coverage script.
"""
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
SPEC = ROOT / 'keel-spec.md'
OUT = ROOT / 'tools/cgen/src/engine/diag_catalog.def'
SEVERITY = {'error': 'K_ERROR', 'warning': 'K_WARNING', 'info': 'K_INFO'}


def catalog():
    text = SPEC.read_text(encoding='utf-8')
    start = text.index('### 6.2 Cat')
    end = text.index('### 6.3', start)
    rows = []
    for line in text[start:end].splitlines():
        if not line.startswith('| `'):
            continue
        cells = line.strip().strip('|').split(' | ')
        ident = cells[0].strip().strip('`')
        # the last three cells are severity, owner and contract; the condition
        # is everything between (it may hold a `|` inside code)
        severity = cells[-3].strip().strip('`')
        assert re.fullmatch(r'[a-z0-9]+(-[a-z0-9]+)*', ident), line
        assert severity in ('error', 'warning', 'info', 'debug'), line
        rows.append((ident, severity))
    ids = [i for i, _ in rows]
    assert len(ids) == len(set(ids)), 'duplicate identifier in the catalog'
    return rows


def render(rows):
    out = ['/* Generated by tools/cgen/gen-diags.py from keel-spec.md section 6.2. Do not edit.',
           '   One X(NAME, "identifier", severity) per diagnostic the translation can emit. */',
           '#define K_DIAG_CATALOG(X) \\']
    live = [(i, s) for i, s in rows if s != 'debug']
    for n, (ident, severity) in enumerate(live):
        name = ident.upper().replace('-', '_')
        tail = ' \\' if n + 1 < len(live) else ''
        out.append('    X(%s, "%s", %s)%s' % (name, ident, SEVERITY[severity], tail))
    return '\n'.join(out) + '\n'


def main():
    rows = catalog()
    if '--list' in sys.argv:
        for ident, severity in rows:
            print(ident, severity)
        return 0
    text = render(rows)
    if '--check' in sys.argv:
        if not OUT.exists() or OUT.read_text() != text:
            print('diag_catalog.def is out of date: run tools/cgen/gen-diags.py', file=sys.stderr)
            return 1
        return 0
    OUT.write_text(text)
    return 0


sys.exit(main())
