#!/bin/sh
# Hand-written oracle for the m0-args-partition task. Not generated by the
# model under test. `make -C tools/cgen` (a separate step in the task's
# acceptance list, run before this script) proves the file fits the real
# build and the engine/tool boundary. This script drives a SEPARATE
# ASan+UBSan instrumented build of the same file for the actual behavioral
# checks — a plain build turns a NULL-deref into a bare "Segmentation
# fault", which is nothing for a retry loop to act on; the sanitizer turns
# it into a file:line report the next attempt can actually read.
set -u

SRC=tools/cgen/src/tool/main.c
ROOTS=tools/cgen/src/tool/roots.c
MATCH_OPT=tools/cgen/src/tool/match_option.c
BASE_RESOLVE=tools/cgen/src/tool/base_resolve.c
CGEN=$(mktemp)
FAKECC=$(mktemp)
FAKECC_LOG="$FAKECC.log"
trap 'rm -f "$FAKECC" "$FAKECC_LOG" "$CGEN"' EXIT

gcc -std=c2x -I tools/cgen/src -I tools/cgen/gen \
    -fsanitize=address,undefined -fno-sanitize-recover=all -g -O0 \
    "$SRC" "$ROOTS" "$MATCH_OPT" "$BASE_RESOLVE" \
    $(find tools/cgen/src -name '*.c' ! -name main.c ! -name roots.c \
          ! -name match_option.c ! -name base_resolve.c) -o "$CGEN"
if [ $? -ne 0 ]; then
    echo "FAIL: sanitizer build failed (see above)"
    exit 1
fi

cat > "$FAKECC" <<EOF
#!/bin/sh
echo "\$@" > "$FAKECC_LOG"
exit 7
EOF
chmod +x "$FAKECC"

failures=0
fail() { echo "FAIL: $1"; failures=$((failures + 1)); }
fail_with_output() { echo "FAIL: $1"; echo "$2"; failures=$((failures + 1)); }

# --- §8.1: version ---
out=$("$CGEN" --cgen-version 2>&1)
code=$?
if [ "$code" != 0 ]; then
    fail_with_output "--cgen-version exit code: got $code" "$out"
elif [ "$out" != "cgen 0.1.0" ]; then
    fail_with_output "--cgen-version output: got '$out'" ""
fi

# --- §8.2: transparent link (no .k source) ---
out=$("$CGEN" --cc="$FAKECC" main.o geom.o -o prog -lm 2>&1)
code=$?
if [ "$code" != 7 ]; then
    fail_with_output "transparent link exit code: got $code, want 7 (the fake cc's)" "$out"
else
    logged=$(cat "$FAKECC_LOG" 2>/dev/null || echo "<no log>")
    [ "$logged" = "main.o geom.o -o prog -lm" ] || fail "transparent link argv: got '$logged'"
fi

# --- §8.8, error 1: multiple-sources ---
out=$("$CGEN" a.k b.k 2>&1)
code=$?
[ "$code" = 2 ] || fail "multiple-sources exit code: got $code"
echo "$out" | grep -q '\[multiple-sources\]' || fail "multiple-sources message must end in the literal text ' [multiple-sources]' (with the brackets) — got '$out', which is missing that suffix"

# --- §8.8, error 2: invalid-option ---
out=$("$CGEN" --profile=c99 hello.k 2>&1)
code=$?
[ "$code" = 2 ] || fail "invalid-option exit code: got $code"
echo "$out" | grep -q '\[invalid-option\]' || fail "invalid-option message must end in the literal text ' [invalid-option]' (with the brackets) — got '$out', which is missing that suffix"

# --- §8.8, error 3: source-in-multiple-roots ---
out=$("$CGEN" -I . -I src src/a.k 2>&1)
code=$?
[ "$code" = 2 ] || fail "source-in-multiple-roots exit code: got $code"
echo "$out" | grep -q '\[source-in-multiple-roots\]' || fail "source-in-multiple-roots message must end in the literal text ' [source-in-multiple-roots]' (with the brackets) — got '$out', which is missing that suffix"

if [ "$failures" = 0 ]; then
    echo "ok"
    exit 0
fi
echo "$failures failure(s)"
exit 1
