#!/bin/sh
# decl-protocol, typedef byref and functions over a protocol (keel-spec §2.2,
# §4.14, §5.1; backend §5.19). Hand-written expectation, from the grammar and
# the backend's naming rule; not generated by the parser under test.
set -u
d=$(mktemp -d)
trap 'rm -rf "$d"' EXIT
mkdir -p "$d/app"
cat > "$d/app/lst.k" <<'K'
module app.lst;
import keel.buffer as buffer;
import keel.slice as slice;
// the protocols come with the prelude (spec §5.1)

pub protocol Seq [IndexPtr, Sliceable];
pub protocol Sized type C { size_t length(C *x); }
pub typedef struct { i32 n; } Shared byref;
pub typedef struct Node { i32 v; struct Node *link; } Node;
pub typedef struct { Node *head; } List;
pub typedef struct { Node *current; } cursor;

pub inline cursor begin(List *l)               { cursor c = { l->head }; return c; }
pub inline bool   has_next(List *l, cursor *c) { return c->current != NULL; }
pub inline i32   *next(List *l, cursor *c)     { i32 *p = &c->current->v; c->current = c->current->link; return p; }

pub size_t count(Traversable C items) { return 0; }

pub size_t use(buffer.buffer i32 *xs, List *l) {
    slice.slice i32 s = slice.of(xs, 1, 2);
    return count(l);
}
K
want=$(cat <<'W'
decl	pub protocol	Seq	-	app/lst.k:6:1
decl	pub protocol	Sized	-	app/lst.k:7:1
decl	pub type	Shared	app_lst_Shared	app/lst.k:8:1
ilha	call	slice.of/3 → keel_slice_of2_keel_buffer_i32	app/lst.k:20:25
ilha	call	count/1 → app_lst_count_app_lst_List	app/lst.k:21:12
W
)
got=$(cd "$d" && "$OLDPWD/tools/cgen/cgen" --base-dir "$OLDPWD/base" --stop-after=parse app/lst.k 2>&1 |
      grep -E '^decl	pub (protocol|type	Shared)|^ilha	call	(slice\.of|count)')
if [ "$got" != "$want" ]; then
    echo "FAIL: protocols"
    printf 'got:\n%s\nwant:\n%s\n' "$got" "$want"
    exit 1
fi
echo ok
