#!/bin/sh
# Stages 4c, 4d and 4f (parser-design §3.2): the defer, foreach, walk and match
# islands and their details (cgen-tool §5.2). Hand-written expectation, from
# the source below and the dump format; not generated by the parser under test.
set -u
d=$(mktemp -d)
trap 'rm -rf "$d"' EXIT
mkdir -p "$d/app"
cat > "$d/app/st.k" <<'K'
module app.st;
import keel.buffer as buffer types;
import keel.range as range types;
import keel.tagged as tagged types;

pub tags Light [RED, AMBER, GREEN];

pub i32 sum(buffer i32 *xs, range r, tagged Light void *s) {
    i32 t = 0;
    defer [now i32 t] t;
    defer t;
    foreach (i32 x, size_t i : xs) t += x;
    foreach (auto v : 0..4) t += (i32)v;
    foreach (size_t v : r) t += (i32)v;
    walk (i32 *p, buffer.cursor c : xs) t += *p;
    match (s) {
        RED: t = 1;
        AMBER:
        GREEN: t = 2;
    }
    return t;
}
K
want=$(cat <<'W'
ilha	defer	now i32 t	app/st.k:10:5
ilha	defer	later	app/st.k:11:5
ilha	foreach	x, i : xs (buffer i32)	app/st.k:12:5
ilha	foreach	v : 0..4	app/st.k:13:5
ilha	foreach	v : r (range)	app/st.k:14:5
ilha	walk	p, c : xs (buffer i32)	app/st.k:15:5
ilha	match	s (tagged Light void): RED AMBER GREEN	app/st.k:16:5
W
)
got=$(cd "$d" && "$OLDPWD/tools/cgen/cgen" --base-dir "$OLDPWD/base" --stop-after=parse app/st.k 2>&1 |
      grep -E '^ilha	(defer|foreach|walk|match)	|error')
if [ "$got" != "$want" ]; then
    echo "FAIL: statements"
    printf 'got:\n%s\nwant:\n%s\n' "$got" "$want"
    exit 1
fi
echo ok
