#!/usr/bin/env python3
"""Writes (or rewrites) the index of a normative document: a list of its
## and ### headings, placed right before the first numbered chapter
("## 1."), between the markers below. Run from the repository root:

    python3 tools/doc/toc.py keel-spec.md keel-c-backend.md
"""
import re
import sys

BEGIN = "<!-- toc: generated by tools/doc/toc.py; do not edit by hand -->"
END = "<!-- /toc -->"


def slug(title, seen):
    s = title.strip().lower()
    s = re.sub(r"[`*_]", "", s)
    s = re.sub(r"[^\w\- ]", "", s)
    s = s.replace(" ", "-")
    n = seen.get(s, 0)
    seen[s] = n + 1
    return s if n == 0 else f"{s}-{n}"


def build(text):
    seen, lines, fence = {}, [], False
    for line in text.splitlines():
        if line.startswith("```"):
            fence = not fence
            continue
        if fence:
            continue
        m = re.match(r"^(#{1,4}) (.+)$", line)
        if not m:
            continue
        level, title = len(m.group(1)), m.group(2)
        anchor = slug(title, seen)
        if level in (2, 3) and title != "Índice":
            indent = "" if level == 2 else "  "
            lines.append(f"{indent}- [{title}](#{anchor})")
    return "\n".join(lines)


def main():
    for path in sys.argv[1:]:
        text = open(path, encoding="utf-8").read()
        if BEGIN in text:
            a = text.index("## Índice")
            b = text.index(END) + len(END)
            text = text[:a] + text[b:].lstrip("\n")
        toc = build(text)
        block = f"## Índice\n\n{BEGIN}\n{toc}\n{END}\n\n"
        m = re.search(r"^## 1\. ", text, re.M)
        text = text[:m.start()] + block + text[m.start():]
        open(path, "w", encoding="utf-8").write(text)


main()
